spring:
  datasource:
    url: jdbc:postgresql://postgresql-container:5432/taskmanagementdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
    level:
      org.flywaydb: debug
